# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Lorenzo
middle_name:
last_name: Bocchio
email: lorenzobocchio31@gmail.com
description: "Statistician based in Aarhus, with a passion for turning complex data into meaningful insights. I will be graduating with my Master's Degree in Statistical Sciences from the University of Bologna at the end of March 2024.My expertise lies in designing and executing both independent and collaborative projects, with a keen focus on innovative data solutions. I am proficient in Python, R, and SQL, tools that I leverage to derive actionable insights and inform data-driven strategies. In addition to my technical skills, I bring experience in cross-cultural communication and partnership management from my current role as the Partnership Manager of Erasmus Student Network Denmark, the Danish national section of the largest student non-profit in Europe. This position has allowed me to develop strong interpersonal skills and an ability to negotiate deals and build relationships across diverse groups. I am a team player with a curious and positive mindset, always eager to embrace new challenges and learning opportunities. I thrive in interdisciplinary environments, where collaborative effort is key to achieving shared goals."

  
footer_text: >
  
keywords:   # add your own keywords or leave empty

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 📊  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://lorenzobocchio.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
theme: jekyll-theme-minimal
