# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: |
  Lorenzo Bocchio
  Statistics | Data Science | NLP
logo: /assets/img/pfp.jpg
 # the website title (if blank, full name will be used instead)
first_name: Lorenzo
middle_name:
last_name: Bocchio
email: lorenzobocchio31@gmail.com
description: |
  **Contact:**
  - Email: [lorenzobocchio31@gmail.com](mailto:lorenzobocchio31@gmail.com)
  - LinkedIn: [My LinkedIn](https://www.linkedin.com/in/lorenzobocchio31/)
  - Current Location: Aarhus, Denmark

  **Languages:** 
  - English (C2)
  - Italian (native)
  - Danish (A1)


  
footer_text: >
  
keywords:   # add your own keywords or leave empty

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 📊  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://lorenzobocchio.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: false # set to true if you want to display last updated in the footer
#impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
theme: jekyll-theme-minimal
